# Site settings
# in the templates available like {{ site.myvariable }}.
title: Download Website
email: minihypov@gmail.com
brand: WithOneTee
headline: Gamer, coder, and Youtuber
description: > # this means to ignore newlines until "baseurl:"
  WithOneTee Download Website
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
copyright: 2016 Whatever Company, Inc. All Rights Reserved.

# Build settings
markdown: kramdown

# Account ids
snapwidget: 247552

# Contacts
email: minihypov@gmail.com


